package sgqr

// SGQROptions represents the options for generating a SGQR string
type SGQROptions struct {
	// UEN number, or +65[mobile number] for mobile numbers
	ReceiverType             string
	MobileOrUENAccountNumber string
	Editable                 bool
	Expiry                   string
	Amount                   string
	SGQRID                   string // Unique SGQR identifier, generated by the SGQR Centralised Repository
	CompanyName              string
	ReferenceNumber          string
}

// PayNowQROptions represents the options for generating a QR string for mobile number PayNow
type PayNowQROptions struct {
	MobileNumber    string
	Editable        bool
	Expiry          string
	Amount          string
	CompanyName     string
	ReferenceNumber string
}

type SGQRDataObject struct {
	ID        string
	Name      string
	MaxLength int
	Value     interface{}
}

type SGQRRootObject struct {
	DataObjects []SGQRDataObject
}
